"""
ocr_index_smac.py — Index scanned SMAC PDFs using Docling with OCR enabled.

Reads pdfs_pending_ocr.txt (generated by bulk_index_smac.py) and processes
each scanned PDF with OCR-enabled Docling for table extraction.

This is a standalone script that directly imports backend modules — it does
NOT go through the FastAPI backend. This avoids HTTP overhead and allows
the OCR-enabled Docling converter to be used separately from the main
(non-OCR) converter.

Usage:
    cd backend/
    python ../dbscripts/ocr_index_smac.py

    # Custom OCR pending file:
    python ../dbscripts/ocr_index_smac.py --pending-file /path/to/pdfs_pending_ocr.txt

    # Dry run (show files, don't process):
    python ../dbscripts/ocr_index_smac.py --dry-run

    # Limit to N files (for testing):
    python ../dbscripts/ocr_index_smac.py --limit 5

    # Specify collection and case-id:
    python ../dbscripts/ocr_index_smac.py --collection SMAC --case-id 0
"""

import os
import sys
import re
import uuid
import time
import sqlite3
import argparse
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Tuple, Any

# Add backend to path
BACKEND_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "backend")
sys.path.insert(0, BACKEND_DIR)
os.chdir(BACKEND_DIR)

# Backend imports (triggers init_db, loads .env)
from config import CHROMA_PATH, EMBED_MODEL
from ollama_client import ollama_embed_batch
from structured_tables import store_smac_report

import chromadb
from pypdf import PdfReader
from rag import clear_documents_by_source


# ---------------------------------------------------------------------------
# Progress DB (SQLite — tracks which files have been OCR-processed)
# ---------------------------------------------------------------------------
OCR_PROGRESS_DB = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".smac_ocr_progress.db")


def _now():
    return datetime.utcnow().isoformat(timespec="seconds")


def open_progress_db(db_path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path, check_same_thread=False)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS ocr_progress (
            file_path TEXT PRIMARY KEY,
            status    TEXT NOT NULL DEFAULT 'pending',
            doc_id    TEXT,
            chunks    INTEGER DEFAULT 0,
            fields    INTEGER DEFAULT 0,
            error     TEXT,
            updated   TEXT
        )
    """)
    conn.commit()
    return conn


def register_ocr_files(conn: sqlite3.Connection, files: list):
    conn.executemany(
        "INSERT OR IGNORE INTO ocr_progress (file_path, status, updated) VALUES (?, 'pending', ?)",
        [(f, _now()) for f in files],
    )
    conn.commit()


def get_ocr_pending(conn: sqlite3.Connection) -> list:
    rows = conn.execute(
        "SELECT file_path FROM ocr_progress WHERE status IN ('pending', 'failed') ORDER BY file_path"
    ).fetchall()
    return [r[0] for r in rows]


def mark_ocr_done(conn: sqlite3.Connection, file_path: str, doc_id: str, chunks: int, fields: int):
    conn.execute(
        "UPDATE ocr_progress SET status='done', doc_id=?, chunks=?, fields=?, error=NULL, updated=? WHERE file_path=?",
        (doc_id, chunks, fields, _now(), file_path),
    )
    conn.commit()


def mark_ocr_failed(conn: sqlite3.Connection, file_path: str, error: str):
    conn.execute(
        "UPDATE ocr_progress SET status='failed', error=?, updated=? WHERE file_path=?",
        (error[:500], _now(), file_path),
    )
    conn.commit()


def get_ocr_stats(conn: sqlite3.Connection) -> dict:
    rows = conn.execute("SELECT status, COUNT(*) FROM ocr_progress GROUP BY status").fetchall()
    return dict(rows)


# ---------------------------------------------------------------------------
# OCR-enabled Docling converter (separate from the non-OCR singleton)
# ---------------------------------------------------------------------------
_ocr_converter = None


def _get_ocr_converter():
    """Initialize Docling with OCR enabled for scanned PDF processing."""
    global _ocr_converter
    if _ocr_converter is not None:
        return _ocr_converter

    from docling.datamodel.base_models import InputFormat
    from docling.datamodel.pipeline_options import (
        PdfPipelineOptions,
        TableFormerMode,
    )
    from docling.document_converter import DocumentConverter, PdfFormatOption
    from docling.backend.pypdfium2_backend import PyPdfiumDocumentBackend

    pipeline_options = PdfPipelineOptions()

    # Enable OCR for scanned documents
    pipeline_options.do_ocr = True

    # Keep table structure detection
    pipeline_options.do_table_structure = True
    pipeline_options.table_structure_options.do_cell_matching = True
    pipeline_options.table_structure_options.mode = TableFormerMode.ACCURATE

    # Disable unnecessary processing
    pipeline_options.generate_page_images = False
    pipeline_options.generate_picture_images = False
    pipeline_options.generate_table_images = False
    pipeline_options.do_picture_classification = False
    pipeline_options.do_picture_description = False
    pipeline_options.do_code_enrichment = False
    pipeline_options.do_formula_enrichment = False

    _ocr_converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(
                pipeline_options=pipeline_options,
                backend=PyPdfiumDocumentBackend,
            )
        }
    )
    print("[OCR] Docling initialized with OCR enabled")
    return _ocr_converter


# ---------------------------------------------------------------------------
# OCR table extraction
# ---------------------------------------------------------------------------
def extract_tables_with_ocr(pdf_path: str) -> Tuple[str, str]:
    """Extract tables from a scanned PDF using Docling with OCR."""
    converter = _get_ocr_converter()
    result = converter.convert(pdf_path)
    doc = result.document

    lines = []
    row_idx = 0
    for table_idx, table in enumerate(doc.tables):
        try:
            df = table.export_to_dataframe(doc=doc)
            if df.empty or len(df) == 0:
                continue

            # Emit column headers as data row if they look like table data
            col_cells = [str(c).strip().replace("\n", " ").replace("\r", " ") for c in df.columns]
            col_deduped = [col_cells[i] for i in range(len(col_cells)) if i == 0 or col_cells[i] != col_cells[i - 1]]
            if col_deduped and any(c.rstrip(". ").isdigit() for c in col_deduped[:1]):
                lines.append(f"Row {row_idx}: {' | '.join(col_deduped)}")
                row_idx += 1

            for r in range(len(df)):
                raw_cells = [str(v).strip().replace("\n", " ").replace("\r", " ") for v in df.iloc[r]]
                deduped = [raw_cells[i] for i in range(len(raw_cells)) if i == 0 or raw_cells[i] != raw_cells[i - 1]]
                cell_text = " | ".join(deduped)
                lines.append(f"Row {row_idx}: {cell_text}")
                row_idx += 1
        except Exception as e:
            print(f"  [OCR] Table {table_idx} failed: {e}")

    table_text = "\n".join(lines) if lines else ""

    # Also extract paragraph text (OCR'd body text)
    para_parts = []
    for text_item in doc.texts:
        t = str(text_item).strip()
        if t and not t.startswith("|") and not t.startswith("<!--"):
            # Extract just the text content from Docling's text object
            if hasattr(text_item, 'text'):
                para_parts.append(text_item.text)
            else:
                para_parts.append(t)
    paragraph_text = "\n".join(para_parts)

    return table_text, paragraph_text


# ---------------------------------------------------------------------------
# SMAC field parser (same logic as _parse_smac_docling in rag.py)
# ---------------------------------------------------------------------------
_NIL_VALUES = frozenset({
    "-", "–", "—", "nil", "-nil-", "n/a", "none",
    "not available", "not applicable", "na", ".", "..", "---",
})


def parse_smac_fields(table_text: str) -> Tuple[List[str], List[dict]]:
    """Parse Docling pipe-separated table output into SMAC KV fields."""
    units = []
    metas = []

    for line in table_text.split("\n"):
        if not line.startswith("Row "):
            continue

        content = line.split(": ", 1)[1] if ": " in line else line
        parts = [p.strip() for p in content.split("|")]
        if len(parts) < 3:
            continue

        serial = parts[0].rstrip(". ")
        field_name = parts[1].strip()
        value = " | ".join(parts[2:]).strip()

        if not re.match(r"^\d+$", serial):
            continue

        # Stop if serial resets (second table)
        if units and int(serial) <= int(metas[-1]["serial_no"]):
            break

        if not field_name or not value:
            continue
        if value.lower().strip(".- ") in _NIL_VALUES:
            continue

        units.append(f"{field_name}: {value}")
        metas.append({"field_name": field_name, "serial_no": serial, "page": 1})

    return units, metas


# ---------------------------------------------------------------------------
# Chunking (same as rag.py)
# ---------------------------------------------------------------------------
def chunk_text(text: str, chunk_size: int = 2000, overlap: int = 140) -> List[str]:
    text = (text or "").strip()
    if not text:
        return []
    overlap = max(0, min(overlap, chunk_size - 1))
    chunks = []
    n = len(text)
    start = 0
    while start < n:
        end = min(start + chunk_size, n)
        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)
        if end >= n:
            break
        next_start = end - overlap
        if next_start <= start:
            next_start = end
        start = next_start
    return chunks


# ---------------------------------------------------------------------------
# Index a single scanned PDF
# ---------------------------------------------------------------------------
def index_scanned_pdf(
    pdf_path: str,
    filename: str,
    collection_name: str,
    chroma_client: chromadb.PersistentClient,
) -> Dict[str, Any]:
    """Process a scanned PDF with OCR and index into ChromaDB + MySQL."""
    doc_id = str(uuid.uuid4())

    # Step 1: OCR + table extraction
    print(f"  [OCR] Processing: {filename}")
    try:
        table_text, paragraph_text = extract_tables_with_ocr(pdf_path)
    except Exception as e:
        return {"ok": False, "error": f"OCR failed: {e}", "filename": filename}

    # Step 2: Parse SMAC fields from table
    smac_units, smac_metas = [], []
    if table_text:
        smac_units, smac_metas = parse_smac_fields(table_text)
        print(f"  [OCR] Extracted {len(smac_units)} structured fields")

    # Step 3: Chunk the OCR'd text for vector search
    all_text = paragraph_text or ""
    # Also try pypdf (sometimes gets partial text even from scanned docs)
    try:
        reader = PdfReader(pdf_path)
        for page in reader.pages:
            page_text = (page.extract_text() or "").strip()
            if page_text:
                all_text += "\n" + page_text
    except Exception:
        pass

    text_chunks = chunk_text(all_text, chunk_size=2000, overlap=140)
    print(f"  [OCR] Text chunks: {len(text_chunks)}, Structured fields: {len(smac_units)}")

    # Combine: text chunks + structured field units
    units = list(text_chunks)
    unit_metas = [{"page": 1} for _ in text_chunks]

    for u, m in zip(smac_units, smac_metas):
        units.append(u)
        unit_metas.append(m)

    if not units:
        print(f"  [OCR] No text extracted even with OCR: {filename}")
        return {"ok": False, "error": "No text extracted with OCR", "filename": filename}

    # Step 4: Embed and store in ChromaDB
    # Cap units
    MAX_UNITS = 800
    MIN_LEN = 10
    cleaned_units = []
    cleaned_metas = []
    for i, u in enumerate(units):
        u2 = u.strip()
        if len(u2) >= MIN_LEN:
            cleaned_units.append(u2)
            cleaned_metas.append(unit_metas[i] if i < len(unit_metas) else {})

    cleaned_units = cleaned_units[:MAX_UNITS]
    cleaned_metas = cleaned_metas[:MAX_UNITS]

    if not cleaned_units:
        return {"ok": False, "error": "All chunks too short", "filename": filename}

    print(f"  [OCR] Embedding {len(cleaned_units)} units...")
    embeddings = ollama_embed_batch(cleaned_units, model=EMBED_MODEL)

    # Get or create ChromaDB collection
    col_name = collection_name
    if len(col_name) < 3:
        col_name = col_name + "_db"
    collection = chroma_client.get_or_create_collection(name=col_name)

    ids = []
    metadatas = []
    documents = []
    for i, (u, m) in enumerate(zip(cleaned_units, cleaned_metas)):
        ids.append(f"{doc_id}_{i}")
        base_meta = {
            "doc_id": doc_id,
            "doc_name": filename,
            "doc_type": "pdf",
            "chunk_index": i,
            "source": "ocr",
        }
        base_meta.update(m or {})
        metadatas.append(base_meta)
        documents.append(u)

    collection.add(ids=ids, embeddings=embeddings, documents=documents, metadatas=metadatas)
    print(f"  [OCR] Stored {len(cleaned_units)} chunks in ChromaDB")

    # Step 5: Store structured fields in MySQL
    if smac_units:
        field_values = []
        for u, m in zip(smac_units, smac_metas):
            fn = m.get("field_name")
            if fn and ": " in u:
                val = u.split(": ", 1)[1]
                sno = m.get("serial_no", "")
                field_values.append({"field_name": fn, "value": val, "serial_no": sno})
        if field_values:
            store_smac_report(doc_id, filename, field_values)
            print(f"  [OCR] Stored {len(field_values)} fields in MySQL")

    return {
        "ok": True,
        "doc_id": doc_id,
        "filename": filename,
        "chunks": len(cleaned_units),
        "fields": len(smac_units),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Index scanned SMAC PDFs using Docling with OCR enabled.",
    )
    parser.add_argument(
        "--folder", default=None,
        help="Folder containing scanned PDFs (recursive scan). Use this OR --pending-file.",
    )
    parser.add_argument(
        "--pending-file", default=None,
        help="Path to pdfs_pending_ocr.txt (default: auto-detect in dbscripts/)",
    )
    parser.add_argument(
        "--collection", default="SMAC",
        help="ChromaDB collection name (default: SMAC)",
    )
    parser.add_argument(
        "--case-id", type=int, default=0,
        help="Case ID (default: 0)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="List files without processing",
    )
    parser.add_argument(
        "--limit", type=int, default=0,
        help="Process only N files (0 = all)",
    )
    parser.add_argument(
        "--reset", action="store_true",
        help="Clear all OCR data from ChromaDB + MySQL + progress DB and start fresh",
    )
    parser.add_argument(
        "--progress-db", default=OCR_PROGRESS_DB,
        help=f"Path to SQLite progress file (default: {OCR_PROGRESS_DB})",
    )

    args = parser.parse_args()

    # Collect files from ALL sources: --folder + --pending-file + auto-detected txt
    SKIP_NAMES = {"report", "reports", "feedback", "attachment", "attachments"}
    all_files = []
    sources = []

    # Source 1: folder (if provided)
    if args.folder:
        folder = Path(args.folder)
        if not folder.is_dir():
            print(f"ERROR: Folder not found: {folder}")
            sys.exit(1)
        raw = list(folder.rglob("*.pdf")) + list(folder.rglob("*.PDF"))
        skipped = 0
        folder_seen = set()
        for p in sorted(raw):
            k = str(p).lower()
            if k not in folder_seen:
                folder_seen.add(k)
                if p.stem.strip().lower() in SKIP_NAMES:
                    skipped += 1
                    continue
                all_files.append(str(p))
        sources.append(f"Folder: {folder} ({len(all_files)} files)")
        if skipped:
            print(f"Skipped {skipped} files from folder (Report/Reports/Feedback/Attachment/Attachments)")

    # Source 2: pending file (explicit or auto-detected)
    pending_path = args.pending_file
    if not pending_path:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        for c in [
            os.path.join(script_dir, "pdfs_pending_ocr.txt"),
            os.path.join(BACKEND_DIR, "pdfs_pending_ocr.txt"),
        ]:
            if os.path.exists(c):
                pending_path = c
                break

    if pending_path and os.path.exists(pending_path):
        with open(pending_path, "r", encoding="utf-8") as f:
            pending_files = [line.strip() for line in f if line.strip()]
        all_files.extend(pending_files)
        sources.append(f"Pending file: {pending_path} ({len(pending_files)} files)")

    if not all_files:
        print("ERROR: No files found. Use --folder and/or ensure pdfs_pending_ocr.txt exists.")
        sys.exit(1)

    source_desc = " + ".join(sources)

    # Deduplicate and validate
    seen = set()
    valid_files = []
    missing_files = []
    for fp in all_files:
        if fp in seen:
            continue
        seen.add(fp)
        if os.path.exists(fp):
            valid_files.append(fp)
        else:
            missing_files.append(fp)

    # ── Reset mode ────────────────────────────────────────────────────────
    if args.reset:
        print("[Reset] Clearing OCR data...")
        # Clear OCR chunks from ChromaDB + MySQL
        try:
            result = clear_documents_by_source(collection_name=args.collection, source="ocr")
            print(f"[Reset] Cleared {result.get('chunks_deleted', 0)} OCR chunks from ChromaDB")
            doc_ids = result.get("doc_ids", [])
            if doc_ids:
                from mysql_db import get_conn as _get_conn
                conn = _get_conn()
                cur = conn.cursor()
                for did in doc_ids:
                    if did:
                        cur.execute("DELETE FROM smac_reports WHERE doc_id = %s", (did,))
                conn.commit()
                cur.close()
                conn.close()
                print(f"[Reset] Cleared {len(doc_ids)} docs from MySQL smac_reports")
        except Exception as e:
            print(f"[Reset] WARNING: ChromaDB/MySQL clear failed: {e}")
        # Delete progress DB
        if os.path.exists(args.progress_db):
            os.remove(args.progress_db)
            print(f"[Reset] Deleted progress DB: {args.progress_db}")
        print("[Reset] Done. Ready for fresh OCR run.\n")

    # Header
    print()
    print("=" * 62)
    print("  ISD Document Intelligence — OCR SMAC Indexer")
    print("=" * 62)
    print(f"  Source        : {source_desc}")
    print(f"  Total entries : {len(all_files)}")
    print(f"  Valid files   : {len(valid_files)}")
    print(f"  Missing files : {len(missing_files)}")
    print(f"  Collection    : {args.collection}")
    print(f"  Progress DB   : {args.progress_db}")
    print(f"  Dry run       : {args.dry_run}")
    if args.limit:
        print(f"  Limit         : {args.limit}")
    print("=" * 62)
    print()

    if missing_files:
        print(f"Missing files (not found on disk):")
        for fp in missing_files[:10]:
            print(f"  {fp}")
        if len(missing_files) > 10:
            print(f"  ... and {len(missing_files) - 10} more")
        print()

    if not valid_files:
        print("No valid files to process.")
        sys.exit(0)

    if args.dry_run:
        print(f"Files to process ({len(valid_files)}):")
        for fp in valid_files:
            print(f"  {fp}")
        sys.exit(0)

    # ── Progress DB ───────────────────────────────────────────────────────
    progress_conn = open_progress_db(args.progress_db)
    register_ocr_files(progress_conn, valid_files)
    pending = get_ocr_pending(progress_conn)
    stats = get_ocr_stats(progress_conn)
    already = stats.get("done", 0)

    if args.limit > 0:
        pending = pending[:args.limit]

    print(f"[Progress] Total: {len(valid_files)}  |  Already done: {already}  |  To process: {len(pending)}")
    print()

    if not pending:
        print("All files already processed. Use --reset to start fresh.")
        progress_conn.close()
        sys.exit(0)

    # Initialize ChromaDB
    from config import CHROMA_PATH
    chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)

    # Process files
    start_time = time.time()
    results = {"ok": 0, "failed": 0, "total_chunks": 0, "total_fields": 0}
    failed_files = []
    total = len(pending)

    for i, file_path in enumerate(pending, 1):
        fname = Path(file_path).name
        print(f"\n[{i:>4d}/{total}] {fname}")

        try:
            result = index_scanned_pdf(
                pdf_path=file_path,
                filename=fname,
                collection_name=args.collection,
                chroma_client=chroma_client,
            )

            if result.get("ok"):
                results["ok"] += 1
                results["total_chunks"] += result.get("chunks", 0)
                results["total_fields"] += result.get("fields", 0)
                mark_ocr_done(progress_conn, file_path, result.get("doc_id", ""),
                              result.get("chunks", 0), result.get("fields", 0))
                print(f"  -> OK: {result.get('chunks', 0)} chunks, {result.get('fields', 0)} fields")
            else:
                results["failed"] += 1
                err = result.get("error", "unknown")
                mark_ocr_failed(progress_conn, file_path, err)
                failed_files.append((fname, err))
                print(f"  -> FAILED: {err}")

        except Exception as e:
            results["failed"] += 1
            mark_ocr_failed(progress_conn, file_path, str(e))
            failed_files.append((fname, str(e)))
            print(f"  -> ERROR: {e}")

    progress_conn.close()

    # Summary
    elapsed = time.time() - start_time
    hrs, rem = divmod(int(elapsed), 3600)
    mns, sec = divmod(rem, 60)

    print()
    print("=" * 62)
    print("  OCR INDEXING COMPLETE")
    print("=" * 62)
    print(f"  Elapsed       : {hrs}h {mns}m {sec}s")
    print(f"  Processed     : {results['ok'] + results['failed']}")
    print(f"  OK            : {results['ok']}")
    print(f"  Failed        : {results['failed']}")
    print(f"  Total chunks  : {results['total_chunks']}")
    print(f"  Total fields  : {results['total_fields']}")
    if results['ok'] > 0:
        avg = elapsed / results['ok']
        print(f"  Avg / file    : {avg:.1f}s")
    print("=" * 62)

    if failed_files:
        print(f"\nFailed files ({len(failed_files)}):")
        for fname, err in failed_files:
            print(f"  {fname}  —  {err}")

        # Write failures log
        fail_log = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ocr_failures.txt")
        with open(fail_log, "w", encoding="utf-8") as f:
            for fname, err in failed_files:
                f.write(f"{fname}\t{err}\n")
        print(f"\nFailures logged to: {fail_log}")


if __name__ == "__main__":
    main()
